name: Assert branch conventions

on:
  pull_request:
    types: [opened]

jobs:
  branch-naming-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-branch-name@v1.0.0
        with:
          allowed_prefixes: "feature/,fix/,performance/,chore/,ci/"
